version: "3"
services:
  postdb:
    container_name: postdb
    image: mysql:8.0.29
    environment:
      MYSQL_DATABASE: tracking_post_db
      MYSQL_USER: user
      MYSQL_PASSWORD: Test2802!
      MYSQL_ROOT_PASSWORD: Test2802!
    ports:
      - "3306:3306"
    networks:
      - trackingpost_net # 해당 네트워크로 편입
    restart: always
  kakaochannel:
    container_name: kakaochannel
    build: ./kakaochannel
    ports:
      - "8082:8082"
#    working_dir: /app #컨테이너에서 명령어가 실행될 위치
#    command: ["java","-jar","/app.jar"] #jar 파일 실행
    command: ["java","-jar","/app.jar"] #jar 파일 실행
    depends_on:
      - postdb
    networks:
      - trackingpost_net # 해당 네트워크로 편입
    restart: always

  externalpost:
    container_name: externalpost
    build: ./externalpost
    expose:
      - "8081"
#    working_dir: ./externalpost #컨테이너로 복사할 작업파일 경로
#    command: [ "./gradlew","bootrun" ]
    command: ["java","-jar","/app.jar"] #jar 파일 실행
    depends_on:
      - postdb
    networks:
      - trackingpost_net # 해당 네트워크로 편입
    restart: always

  servicehome:
    container_name: servicehome
    build: ./servicehome
    expose:
      - "8080"
#    working_dir: ./servicehome #컨테이너로 복사할 작업파일 경로
#    command: [ "./gradlew","bootrun" ]
    command: ["java","-jar","/app.jar"] #jar 파일 실행
    depends_on:
      - postdb
    networks:
      - trackingpost_net # 해당 네트워크로 편입
    restart: always

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    expose:
      - "2181"
    networks:
      - trackingpost_net # 해당 네트워크로 편입
    restart: always
  kafka:
    build: ./kafka-docker
    container_name: kafka
    expose:
      - "9092"
    environment:  #환경변수
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "posttopic"
    depends_on:
      - zookeeper
    networks:
      - trackingpost_net # 해당 네트워크로 편입
    restart: always

networks: #네트워크 새로 등록
  trackingpost_net:
    driver: bridge